### ISSUE TITLE
Testing framework: Which and what to test?

### ISSUE THREAD

**Issue by iDuuck** [fintory/boot-next#14]
## Motivation

We have discussed multiple times in our weekly's that we would like to tackle testing in our daily development.

## What to test?

- E2E/Integration Tests (probably)
- Unit Tests
- Snapshot Tests

### Base Testing Framework

I would suggest to go with `Jest` as our base testing framework, since it is well proven and has the best integration into `@testing-framework/react`.

### React (Snapshot/Unit) Testing

- [`enzyme`](https://github.com/enzymejs/enzyme)
- [`@testing-framework/react`](https://testing-library.com/docs/react-testing-library/intro)

### E2E/Integration Testing

- WebdriverJS
- Protractor
- WebdriverIO
- NightwatchJS
- Cypress
- TestCafe
- Puppeteer

<details>
<summary>Comparison</summary>

![image](https://user-images.githubusercontent.com/325241/94416316-fb62df00-017e-11eb-9597-37c66f186533.png)

</details>

**Comment by chmtt** [comment]
Since i've no experience in writing tests at all i can't give any real advise here.

However, in the Comparison Sheet **TestCafe** looks like the best option to me in case of available options.
Additional **Puppeteer** would also be interesting, as discussed in our meeting.

**Comment by iDuuck** [comment]
Why does "TestCafe" look good from what you see in the comparison table? I don't like that there is a "custom implementation" and no integration into a test framework at all. Looking at this the WebdriverIO and JS variants look much better for me.

**Comment by iDuuck** [comment]
## Discussion from 11-06-2020 (Team Development @ Fintory)

### E2E Testing

We decided to go with **Puppeteer** for this one. We are using the **headless-recorder** for implementing basic tests, but also writing our own, once we are ready with the development of specific features.

### Unit Testing

We are going to use **Jest** as our base testing framework, since it works best with our chosen testing framework for React: **@testing-framework/react**.


@LoRaetz Please open up a Pull Request with the implementation of the tests (both unit tests and e2e tests).
