### ISSUE TITLE
Update Next.js to newest version (v10)

### ISSUE THREAD

**Issue by iDuuck** [fintory/boot-next#27]

**Comment by visualcookie** [comment]
We run on `latest` anyways. If you re-run `yarn`, it would always get the latest stable version.

**Comment by iDuuck** [comment]
@visualcookie We shouldn't use something like "latest" in our package.json, since this can break everything with just one deployment (without changing something). 

Imagine a breaking change is released, and you are telling NPM "I want the `latest` version". You are automatically pulling the breaking change, and you don't know, why the code is broken.
